services:
    pg-database:
        image: postgres
        restart: always
        volumes:
            - ./../db-data:/var/lib/postgresql/data/
        networks:
            - mtg-lounge
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: example
            POSTGRES_DB: mtg_lounge

    j-server:
        image: maven
        depends_on:
            - pg-database
        volumes:
            - ./../j-server:/server
        networks:
            - mtg-lounge
        command: >
            sh -c "
                cd /server
                mvn spring-boot:run
            "

    ts-client:
        image: node
        depends_on:
            - pg-database
        volumes:
            - ./../client:/client
        networks:
            - mtg-lounge
        ports:
            - "5173:5173"
        command: >
            sh -c "
                cd /client
                npm install
                npm run dev
            "

networks:
  mtg-lounge:
    driver: bridge
